import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'
import './globals.css'
import { ContextProvider, QueryProvider, ToastProvider } from '@/providers'

const font = Rubik({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'VNK Management',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
      <QueryProvider>
          <ContextProvider>
            <ToastProvider />
            {children}
          </ContextProvider>
        </QueryProvider>
      </body>
    </html>
  )
}
